version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    restart: always
    ports:
      - "27018:27017"  # Expose MongoDB on the default port
    volumes:
      - mongodb_data:/data/db  # Persist data locally
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Admin username
      MONGO_INITDB_ROOT_PASSWORD: admin123  # Admin password

  resume_optimizer_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_optimizer_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27018  # MongoDB connection URI

volumes:
  mongodb_data:
