version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    restart: always
    ports:
      - "27018:27017"  # Expose MongoDB on the default port
    volumes:
      - mongodb_data:/data/db  # Persist data locally
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Admin username
      MONGO_INITDB_ROOT_PASSWORD: admin123  # Admin password

volumes:
  mongodb_data:
